apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.32.2/controller.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
