apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
