apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/secrets
  - ../../bases/database
  - ../../bases/server
  - ../../namespace

namespace: tpl-phoenix-pg-k8s-tilt
