apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tpl-phoenix-pg-k8s-tilt
spec:
  project: default
  source:
    path: kustomization/overlays/prod
    repoURL: "https://github.com/skaramicke/tpl-phoenix-pg-k8s-tilt"
    targetRevision: HEAD
  destination:
    namespace: tpl-phoenix-pg-k8s-tilt
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
